README.md
src/backup.sh
src/entrypoint.sh

Allow passing custom arguments to minio client

---

.circleci/config.yml
Dockerfile
Makefile
README.md

Build image for arm architectures

---

README.md
src/backup.sh

Support Docker in Swarm mode

---

README.md
cmd/backup/main.go
go.mod
go.sum

Enable sending out email notifications on failed backups

---

cmd/backup/main.go

Previously, a failure on uploading backups to remote backends would leave local artifacats around.

Ensure script always tries to remove local artifacts even when backup failed

---

cmd/backup/main.go

Previously, symlinks would be included in the set of candidates, but would
be skipped when pruning. This could lead to a wrong number of candidates
being printed in the log messages.

Exclude symlinks from candidates when pruning local files

---

cmd/backup/main.go

Picking up the discussion in https://github.com/offen/docker-volume-backup/pull/32#discussion_r742646255

Reuse hook mechanism for scheduling clean up tasks

---

README.md
cmd/backup/main.go
test/compose/docker-compose.yml
test/compose/run.sh

Allow for env substitution in backup filename

---

README.md
cmd/backup/main.go
go.mod
go.sum
test/compose/docker-compose.yml
test/compose/run.sh

Hi,
I did find time to implement WebDav functionality. (:  
Unfortunately the size of the docker image went from ~12mb to ~26mb. Hope this is not much of a deal. :D  
I did not add test cause I wasnt sure... Do we need a publicly available WebDav server?
Closes #47

Support Nextcloud / WebDav

---

README.md
cmd/backup/main.go

Allow path to be set for bucket storage

---

README.md
cmd/backup/script.go

Supporting proxied Docker APIs through DOCKER_HOST

---

README.md

Add some documentation for using DOCKER_HOST as per #68, #69, #70

Add DOCKER_HOST documentation

---

README.md

update custom docker host documentation for pre/post commands

---

cmd/backup/script.go

Consider S3 Path when selecting candidates for pruning

---

cmd/backup/script.go

List objects recursively when selecting candidates from S3

---

go.mod
go.sum

Update webdav client library

---

README.md
cmd/backup/config.go
cmd/backup/script.go
test/compose/docker-compose.yml

Allow disabling of certificate verification for WebDAV

---

README.md
cmd/backup/config.go
test/compose/docker-compose.yml
test/compose/run.sh

Change default value for SSH identity file

---

cmd/backup/notifications.go
docs/NOTIFICATION-TEMPLATES.md
test/notifications/docker-compose.yml
test/notifications/notifications.tmpl
test/notifications/run.sh

Add env template helper

---

entrypoint.sh

Make crond log to stderr so Docker can forward it

---

README.md
cmd/backup/config.go
cmd/backup/script.go

feat: Add storage class header

---

entrypoint.sh

Delete existing crontab before appending entries per conf.d

---

entrypoint.sh

Tweaking what was fixed in #140

Use crontab command to recreate empty tab file

---

.dockerignore
Dockerfile
cmd/backup/config.go
cmd/backup/hooks.go
cmd/backup/lock.go
cmd/backup/notifications.go
cmd/backup/script.go
cmd/backup/stats.go
cmd/backup/util.go
internal/storage/local/local.go
internal/storage/s3/s3.go
internal/storage/ssh/ssh.go
internal/storage/storage.go
internal/storage/webdav/webdav.go
internal/utilities/util.go

Factor out storage implementations

---

cmd/backup/script.go
cmd/backup/stats.go
internal/storage/webdav/webdav.go

Run copying and pruning against multiple storages in parallel

---

internal/storage/s3/s3.go

Call ListObjects without WithMetadata option

---

internal/storage/webdav/webdav.go

Non-streaming upload to WebDAV fails on big files

---

cmd/backup/script.go

TaskTemplate.ForceUpdate is a counter

---

go.mod
go.sum

Resolves https://github.com/offen/docker-volume-backup/security/dependabot/20

Bump Docker client

---

cmd/backup/script.go
internal/storage/azure/azure.go
internal/storage/dropbox/dropbox.go
internal/storage/local/local.go
internal/storage/s3/s3.go
internal/storage/ssh/ssh.go
internal/storage/storage.go
internal/storage/webdav/webdav.go
test/dropbox/run.sh

Pruning method logs nonsensical configuration values

---

test/lock/docker-compose.yml
test/lock/run.sh

Adds a test case for the fix in #339

Add test case for exclusive file lock

---

cmd/backup/script.go

Remove stray log statement

---

cmd/backup/stop_restart.go

Result of query for services is used before handling possible error

---

go.mod
go.sum

Manually fixes https://github.com/offen/docker-volume-backup/security/dependabot/29

Update docker/docker package

---

cmd/backup/config.go
cmd/backup/script.go
docs/reference/index.md
internal/storage/azure/azure.go
test/azure/docker-compose.yml

Add support for Azure storage access tiers

---

cmd/backup/encrypt_archive.go
docs/reference/index.md
go.mod
go.sum
test/age-publickey/run.sh

Support passing standard ssh keys to age encryption

---

test/age-passphrase/docker-compose.yml
test/age-publickey/docker-compose.yml
test/azure/docker-compose.yml
test/certs/docker-compose.yml
test/cli/run.sh
test/collision/docker-compose.yml
test/commands/docker-compose.yml
test/confd/docker-compose.yml
test/dropbox/docker-compose.yml
test/extend/docker-compose.yml
test/gpg-asym/docker-compose.yml
test/gpg/docker-compose.yml
test/local/docker-compose.yml
test/lock/docker-compose.yml
test/pgzip/run.sh
test/proxy/docker-compose.swarm.yml
test/proxy/docker-compose.yml
test/pruning/docker-compose.yml
test/s3/docker-compose.yml
test/secrets/docker-compose.yml
test/services/docker-compose.yml
test/ssh/docker-compose.yml
test/swarm/docker-compose.yml
test/tar/docker-compose.yml
test/user/docker-compose.yml
test/webdav/docker-compose.yml
test/zstd/run.sh

Always use read only socket mount in tests

---

internal/storage/local/local.go
internal/storage/ssh/ssh.go
internal/storage/webdav/webdav.go

Directories aren't excluded from pruning logic

---

docs/reference/index.md

Link to Dropbox from config reference is outdated
