offen/docker-volume-backup

README.md
cmd/backup/main.go
go.mod
go.sum

if during backup, the content of the backup folder continues to change, tar returns a fatal error
```
level=error msg="Fatal error running backup: takeBackup: error compressing backup folder: archive/
tar: write too long"
```
this is because tar create a header containing files to be compressed, and write their size in header. But in actual compressing, it find file size has changed.
If we stop the container during backup, this situation should not happen, however in my scenario, it is desirable that we keep container running. Unfortunately this results in occasional backup failure due to the continuously growing logs files in my backup folder.

create a snapshot before creating tar archive

---

README.md

Edited the "Restoring a volume from a backup" section example to be able to better differentiate between the names of the temporary restore container and the name of the mounted restore volume.
New example container name: temp_restore_container
The restore volume name remains the same: backup_restore
Also changed "one-off container" to "once-off container".

Updated README.md "Restoring..." section example

---

cmd/backup/script.go

Hi, it's me again! I noticed that my backups strangely always took 0 seconds, so I investigated and found this bug.

Fixed TookTime

---

cmd/backup/script.go

Currently, the `BACKUP_PRUNING_PREFIX` is not respected when pruning WebDAV storages.

Consider prefix rules when pruning WebDAV storages

---

test/swarm/docker-compose.yml

This is needed since `offen/offen:latest` contains a healthcheck (which would mean we need to wait 2 minutes for all containers to come back to life in the test)

Disable healthcheck in swarm test

---

README.md
cmd/backup/exec.go
cmd/backup/main.go
cmd/backup/script.go
test/commands/docker-compose.yml

Fine grained labels

---

README.md
test/commands/docker-compose.yml
test/commands/run.sh

Adds a test case for the behavior discussed in #129

Add test case for exec label

---

README.md
cmd/backup/config.go
cmd/backup/script.go
test/secret/docker-compose.yml
test/secret/run.sh
test/swarm/run.sh

Docker Swarm allows the user to define secrets, that are encoding and used to store secrets.
Minio already supports them, by supplying environment variables ending in _FILE.
This PR allows AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to be configured in a similar way.

add aws secret handling

---

README.md
cmd/backup/exec.go
test/extend/Dockerfile
test/extend/docker-compose.yml
test/extend/run.sh

Pass file location to lifecycle commands

---

test/commands/docker-compose.yml
test/commands/run.sh

The old pattern created some confusion in #202 as it's needlessly complicated. This uses the same simple pattern in all tests throughout.

Local directory can be used instead of volume for storing test artifact

---

go.mod
go.sum

Fixes #49
Package `copy` will now silently ignore `os.IsNotExist` errors, preventing this image to fail on volatile file systems.

Update of package copy does not fail on deleted files

---

.github/workflows/test.yml
Dockerfile

This removes an unneeded layer from the Docker image.

Entrypoint permissions can be set on COPY

---

Dockerfile

Workaround until #241 is ready to merge.

Current Docker client breaks in Go 1.20.6

---

Dockerfile
cmd/backup/exec.go
cmd/backup/script.go
go.mod
go.sum

When built with Go 1.20.6 the image starts breaking because of https://github.com/moby/moby/issues/45935

Current Docker client breaks in newer Go versions

---

cmd/backup/exec.go
cmd/backup/lock.go
cmd/backup/main.go
cmd/backup/script.go
go.mod

This is now possible since #246

Drop logrus dependency, log using slog package from stdlib

---

README.md
cmd/backup/archive.go
cmd/backup/config.go
cmd/backup/script.go
go.mod
test/cli-zstd/run.sh

Hi, 
I took a stab at adding zstd support in a way that keeps gzip as default to maintain backward compatibility:
- added BACKUP_COMPRESSION parameter (gzip/zstd)
- updated BACKUP_FILENAME to accept '<ext>' for extension that will dynamically change to `tar.gz` or `tar.zst` depending on compression
- added a build test `cli-zstd`
Please let me know if you require any additional changes.
Real world test:
```
backups  | time=2023-08-17T19:29:00.451-05:00 level=INFO msg="Stopping 3 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 16 running container(s)."
backups  | time=2023-08-17T19:30:02.818-05:00 level=INFO msg="Created backup of `/backup` at `/tmp/backup-2023-08-17T19-29-00.tar.zst`."
backups  | time=2023-08-17T19:30:04.637-05:00 level=INFO msg="Restarted 3 …
```

Add support for zstd compression

---

cmd/backup/script.go

While implementing a new storage backend for Dropbox, I realized that any `b.Log()` **inside** the storage backends doesn't output anything. Now everything works as expected again.

Fix storage backends not outputting any info logs

---

cmd/backup/script.go
internal/storage/azure/azure.go
internal/storage/dropbox/dropbox.go
internal/storage/local/local.go
internal/storage/s3/s3.go
internal/storage/ssh/ssh.go
internal/storage/storage.go
internal/storage/webdav/webdav.go

As we have a structured logger around, we can also leverage it.

Print context in log field instead of prepending to message

---

test/pruning/docker-compose.yml
test/pruning/run.sh
test/test.sh

In CI, tests often seem to hang when the sandbox container fails to be created (the reason for why seems not clear to me, maybe related to https://github.com/moby/moby/issues/12547)

Retry creation of sandbox container

---

docs/how-tos/manual-trigger.md

Hello, just a minor fix for the docs heading I picked up on when reading it. Cheers

Updated Docs subheading mispelling

---

docs/how-tos/run-custom-commands.md
docs/index.md

Include requirement for docker socket and the need to use EXEC_LABEL if you are running multiple copies
Fixes #287

docs: Update the custom commands documentation

---

internal/storage/ssh/ssh.go

Concurrent Writes enabled
Suggested in https://github.com/pkg/sftp/issues/472#issuecomment-930022883
Uploads are 50x faster then before.
4 GiB file takes 5 hours before concurrent writes (~200KB/s). Now it takes like 10 mins (~10MB/s) on my ISP

Performance optimization for sshStorage

---

test/test.sh

It seems calling `docker info` within the DinD container hangs from time to time, making the tests stall when run in CI. This PR tries to solve this by having the call timeout after 5s, retrying again. So far, all runs after the change passed without stalling.

Guard DinD docker info call with timeout

---

cmd/backup/notifications.go
docs/how-tos/set-up-notifications.md

This adds the `toJSON` template function to notifications, allows the template data to JSON serialized and adds a built in default JSON template (simply `{{ . | toJSON }}`).
Useful if want to format a message in a third-party system according to certain rules.

Add method for converting object to JSON in template

---

cmd/backup/main.go

Working on #333 I noticed the script would silently exit 1 when a nil pointer is dereferenced. This PR adds logging for such cases, making the sudden exit a lot less mysterious.

Panic handling does not log reason for script being halted

---

cmd/backup/main.go

It seems #263 broke the file lock as it wrapped the `unlock()` call in `must`, which means it would not get deferred anymore.

Exclusive file lock is released prematurely

---

cmd/backup/stop_restart.go
docs/how-tos/use-custom-docker-host.md
test/proxy/docker-compose.swarm.yml
test/proxy/docker-compose.yml
test/proxy/run.sh

Document socket-proxy permissions, return early when update failed on scaling down

---

Dockerfile
cmd/backup/config.go
cmd/backup/configProvider.go
cmd/backup/config_provider.go
cmd/backup/main.go
cmd/backup/script.go
docs/reference/index.md
go.mod
go.sum

Closes #268
Allows the application to take control of the scheduling instead of relying on crond.
- Tries to read config from environment variables
- Reads all the files under `/etc/dockervolumebackup/conf.d` and each creates a new job
- Without `--foreground` flag, returns to old behaviour

Move cron scheduling inside application

---

cmd/backup/config_provider.go
cmd/backup/cron.go
cmd/backup/exec.go
cmd/backup/main.go
cmd/backup/script.go
test/confd/run.sh

This is mostly just me experimenting with alternative approaches for propagating errors through the application, not sure if this will be merged or not right now.

Hoist control for exiting script a level up

---

cmd/backup/config_provider.go
cmd/backup/main.go
cmd/backup/script.go
test/confd/01backup.env
test/confd/02backup.env
test/confd/03never.env
test/confd/docker-compose.yml

Env vars should propagate when using `conf.d`

---

.github/workflows/deploy-docs.yml

This PR changes the workflow to rebuild the docs on github-pages to only run, when content inside the `docs/` folder is changed. Currently with every push on main the docs are rebuilt, even when no changes have been made.

Conditionally run docs-pages-build

---

.github/workflows/release.yml

i'm using [Renovate](https://github.com/renovatebot/renovate) to automatically update dependencies. Renovate (and similar tools as well) support the docker label `org.opencontainers.image.source`, also known as [OCI](https://github.com/opencontainers/image-spec/blob/main/annotations.md) labels to point to sources and add the release notes in the created PRs --> see for example a PR for [tandoor](https://github.com/TandoorRecipes/recipes):
I noticed, that this docker-volume-backup currently doesn't leverage these labels and implemented them.
When possible i tried to stick to variables instead of hardcoding informations to keep the package dynamically, in case someone forks and wants to distribute it by himself.
Furthermore i kind of reworked the tagging code and replaced it with the …

add OCI labels, rework tagging

---

cmd/backup/config_provider.go
cmd/backup/config_provider_test.go
cmd/backup/testdata/comments.env
test/confd/01backup.env

Closes #373 
Currently, all lines in a file from `conf.d` will be passed to `shell.Expand` no matter if they are comments or not. This is not a problem per se, but as `shell.Expand` will refuse to do command substitution (as to prevent execution of arbitrary code), comments containing either `$(cmd)` or ``cmd`` style commands will raise an error.
As there does not seem to be a way to adjust the behavior of `shell.Expand` further, this PR fixes the issue by skipping lines that are obviously comments.

Lines from conf files that are comments should not be passed to shell.Expand

---

cmd/backup/exec.go

Also forward exec output when failing to demultiplex

---

cmd/backup/config.go
cmd/backup/script.go
docs/reference/index.md
internal/storage/azure/azure.go

Allow authentication using connection string when targeting Azure Blob Storage

---

docs/how-tos/set-up-dropbox.md
docs/recipes/index.md

Updated text for explanation of DROPBOX_REMOTE_PATH environment variable usage, accordingly to how the Dropbox App was scoped during creation.
Minor edit to the sample variable value provided for DROPBOX_REMOTE_PATH in the related recipe, for alignment with update done to the how-to.
For more details, please see the discussion on #472

Documentation update for DROPBOX_REMOTE_PATH environment variable

---

.github/workflows/golangci-lint.yml
.github/workflows/unit.yml
.golangci.yml
cmd/backup/archive.go
cmd/backup/config_provider.go
cmd/backup/config_provider_test.go
cmd/backup/exec.go
cmd/backup/stop_restart.go
go.mod
internal/storage/dropbox/dropbox.go
internal/storage/googledrive/googledrive.go
internal/storage/local/local.go
internal/storage/ssh/ssh.go

The current version of golangci-lint is breaking a lot of builds recently by simply timing out, so let me try updating this as a start.

Update golangci integration

---

docs/reference/index.md
internal/storage/ssh/ssh.go

When using SSH storage, ensure destination directory exists.

Ensure destination exists when using SSH storage
